# See <https://pre-commit.com> for more information
# See <https://pre-commit.com/hooks.html> for more hooks
repos:
  - repo: local
    hooks:
      - id: save-last-commit-message
        name: Save last commit message to file
        entry: ./nixos-modules/features/generations/save-last-commit-message.sh
        language: script
        stages: [commit-msg]
        verbose: true

default_install_hook_types:
  - pre-commit
  - commit-msg
